site_name: BentoBox 中文维基
copyright: "© Copyright 2017-2021 Tastybento, Poslovitch and the BentoBoxWorld community (CC-BY 4.0)."
repo_url: https://github.com/BentoBoxWorld/BentoBox
repo_name: BentoBoxWorld/BentoBox
edit_uri: ""
nav:
    - Home: index.md
    - "BentoBox 是个啥?":
        - Team Handling: BentoBox/About/Teams.md
        - Protection: BentoBox/About/Protections.md
    - FAQ: FAQ.md
    - Game Modes:
        - BSkyBlock: gamemodes/BSkyBlock/index.md
        - Boxed: gamemodes/Boxed/index.md
        - AcidIsland: gamemodes/AcidIsland/index.md
        - SkyGrid: gamemodes/SkyGrid/index.md
        - CaveBlock: gamemodes/CaveBlock/index.md
        - AOneBlock: gamemodes/AOneBlock/index.md
    - Addons:
        - Bank: addons/Bank/index.md
        - Biomes: addons/Biomes/index.md
        - Border: addons/Border/index.md
        - CauldronWitchery: addons/CauldronWitchery/index.md
        - Challenges: addons/Challenges/index.md
        - Chat: addons/Chat/index.md
        - CheckMeOut: addons/CheckMeOut/index.md
        - ControlPanel: addons/ControlPanel/index.md
        - DimensionalTrees: addons/DimensionalTrees/index.md
        - ExtraMobs: addons/ExtraMobs/index.md
        - Greenhouses: addons/Greenhouses/index.md
        - InvSwitcher: addons/InvSwitcher/index.md
        - IslandFly: addons/IslandFly/index.md
        - Level: addons/Level/index.md
        - Likes: addons/Likes/index.md
        - Limits: addons/Limits/index.md
        - MagicCobblestoneGenerator: addons/MagicCobblestoneGenerator/index.md
        - TwerkingForTrees: addons/TwerkingForTrees/index.md
        - Visit: addons/Visit/index.md
        - VoidPortals: addons/VoidPortals/index.md
        - Warps: addons/Warps/index.md
        - Upgrades: addons/Upgrades/index.md
    - "Tutorials – Generic":
        - "How To Install": BentoBox/Install-Bentobox.md
        - "Set a BentoBox world as the server's default world": BentoBox/Set-a-BentoBox-world-as-the-server-default-world.md
        - "Database transition": BentoBox/Database-transition.md
    - "Tutorials – API":
        - "Create an Addon": Tutorials/api/Create-an-addon.md
        - "Config API": BentoBox/Config-API.md
        - "Database API": BentoBox/Database-API.md
        - "Metadata API": BentoBox/MetadataAPI.md
        - "Get Data From Addons": BentoBox/Request-Handler-API---How-plugins-can-get-data-from-addons.md
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: green
  icon:
    repo: fontawesome/brands/git-alt
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BentoBoxWorld
      name: GitHub 上的 BentoBoxWorld
    - icon: fontawesome/brands/jenkins
      link: https://ci.bentobox.world
      name: CodeMC CI 上的 BentoBoxWorld
    - icon: fontawesome/brands/discord
      link: https://discord.bentobox.world
      name: BentoBoxWorld 的 Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCPaNnfxhr1-wCy0KBs9PLdQ
      name: BentoBoxWorld 的 YouTube
    - icon: fontawesome/solid/heart
      link: https://github.com/sponsors/tastybento
      name: 在 GitHub 上赞助原作者 tastybento
    - icon: fontawesome/solid/pen
      link: https://github.com/JeansouLiu/BentoBox-docs-Chinese-translation
      name: 帮助改进此翻译
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.escapeall
  - pymdownx.progressbar
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: "#"
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
  - minify:
      minify_html: true
  - macros
